"""empty message

Revision ID: 36b328c93986
Revises: dbf05fedfa2e
Create Date: 2023-03-03 11:46:18.045993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36b328c93986'
down_revision = 'dbf05fedfa2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Goods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Goods', schema=None) as batch_op:
        batch_op.drop_column('image_name')

    # ### end Alembic commands ###
