"""empty message

Revision ID: 55ce4560fb3f
Revises: 
Create Date: 2023-03-03 09:13:25.186552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55ce4560fb3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('descreption', sa.String(length=420), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('matherial', sa.String(length=75), nullable=True),
    sa.Column('type', sa.String(length=80), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Goods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Goods_name'), ['name'], unique=True)

    with op.batch_alter_table('Clothes_Goods', schema=None) as batch_op:
        batch_op.drop_index('ix_Clothes_Goods_descreption')
        batch_op.drop_index('ix_Clothes_Goods_matherial')
        batch_op.drop_index('ix_Clothes_Goods_name')
        batch_op.drop_index('ix_Clothes_Goods_price')
        batch_op.drop_index('ix_Clothes_Goods_size')

    op.drop_table('Clothes_Goods')
    with op.batch_alter_table('Food_Goods', schema=None) as batch_op:
        batch_op.drop_index('ix_Food_Goods_descreption')
        batch_op.drop_index('ix_Food_Goods_name')
        batch_op.drop_index('ix_Food_Goods_price')

    op.drop_table('Food_Goods')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Food_Goods',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), nullable=True),
    sa.Column('descreption', sa.VARCHAR(length=80), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Food_Goods', schema=None) as batch_op:
        batch_op.create_index('ix_Food_Goods_price', ['price'], unique=False)
        batch_op.create_index('ix_Food_Goods_name', ['name'], unique=False)
        batch_op.create_index('ix_Food_Goods_descreption', ['descreption'], unique=False)

    op.create_table('Clothes_Goods',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=45), nullable=True),
    sa.Column('descreption', sa.VARCHAR(length=120), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('size', sa.VARCHAR(length=10), nullable=True),
    sa.Column('matherial', sa.VARCHAR(length=75), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Clothes_Goods', schema=None) as batch_op:
        batch_op.create_index('ix_Clothes_Goods_size', ['size'], unique=False)
        batch_op.create_index('ix_Clothes_Goods_price', ['price'], unique=False)
        batch_op.create_index('ix_Clothes_Goods_name', ['name'], unique=False)
        batch_op.create_index('ix_Clothes_Goods_matherial', ['matherial'], unique=False)
        batch_op.create_index('ix_Clothes_Goods_descreption', ['descreption'], unique=False)

    with op.batch_alter_table('Goods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Goods_name'))

    op.drop_table('Goods')
    # ### end Alembic commands ###
