"""changed index and price

Revision ID: d258f1bf8644
Revises: 409f849e49e8
Create Date: 2023-03-05 20:33:48.840454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd258f1bf8644'
down_revision = '409f849e49e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Goods', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_Goods_descreption'), ['descreption'], unique=False)
        batch_op.create_index(batch_op.f('ix_Goods_image_name'), ['image_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_Goods_in_stock'), ['in_stock'], unique=False)
        batch_op.create_index(batch_op.f('ix_Goods_matherial'), ['matherial'], unique=False)
        batch_op.create_index(batch_op.f('ix_Goods_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_Goods_publish_date'), ['publish_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_Goods_quantity'), ['quantity'], unique=False)
        batch_op.create_index(batch_op.f('ix_Goods_size'), ['size'], unique=False)
        batch_op.create_index(batch_op.f('ix_Goods_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Goods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Goods_type'))
        batch_op.drop_index(batch_op.f('ix_Goods_size'))
        batch_op.drop_index(batch_op.f('ix_Goods_quantity'))
        batch_op.drop_index(batch_op.f('ix_Goods_publish_date'))
        batch_op.drop_index(batch_op.f('ix_Goods_price'))
        batch_op.drop_index(batch_op.f('ix_Goods_matherial'))
        batch_op.drop_index(batch_op.f('ix_Goods_in_stock'))
        batch_op.drop_index(batch_op.f('ix_Goods_image_name'))
        batch_op.drop_index(batch_op.f('ix_Goods_descreption'))
        batch_op.alter_column('price',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
